name: my_date check
on: 
   workflow_dispatch:
   push:
      tags:
         - checkMe*
jobs:
   run-instructor-tests:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: python3 -m unittest my_date_test.py
